/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BCDeimosContract } from "./BCDeimosContract";
export * as factories from "./factories";
export { BCDeimosContract__factory } from "./factories/BCDeimosContract__factory";
